name: Reproduce grpc/grpc#33361

on:
  - push
  - workflow_dispatch

env:
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1

jobs:
  error:
    strategy:
      matrix:
        runner: [macos-latest, ubuntu-latest]
        include-module: [ON, OFF]
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3

      - uses: Homebrew/actions/setup-homebrew@master
        with:
          test-bot: false

      - name: Check out unpatched gRPC version
        run: |
          cd "$(brew --repository homebrew/core)"
          git checkout 60b65d5104308b263b04d49dad8ff07d3776881a

      - run: brew install cmake grpc

      - run: cmake . -DINCLUDE_FIND_DEPENDENCY_MACRO_MODULE="${{ matrix.include-module }}"
